DISEASES = {
    "Cystic Fibrosis": "autosomal_recessive",
    "Huntington Disease": "autosomal_dominant",
    "Hemophilia": "x_linked_recessive",
    "Color Blindness": "x_linked_recessive",
    "Sickle cell anemia": "autosomal_recessive",
    "Thalassemia": "autosomal_recessive",
    "Tay-Sachs disease": "autosomal_recessive",
    "Phenylketonuria (PKU)": "autosomal_recessive",
    "Spinal muscular atrophy": "autosomal_recessive",
    "Galactosemia": "autosomal_recessive",
    "Wilson’s disease": "autosomal_recessive",
    "Marfan syndrome": "autosomal_dominant",
    "Achondroplasia": "autosomal_dominant",
    "Neurofibromatosis type 1": "autosomal_dominant",
    "Autosomal dominant polycystic kidney disease": "autosomal_dominant",
    "Familial hypercholesterolemia": "autosomal_dominant",
    "Duchenne muscular dystrophy": "x_linked_recessive",
    "Becker muscular dystrophy": "x_linked_recessive",
    "G6PD deficiency": "x_linked_recessive",
    "Rett syndrome": "x_linked_dominant",
    "Fragile X syndrome": "x_linked_dominant",
    "Hypo~phosphatemic rickets": "x_linked_dominant",
    "Leber’s hereditary optic neuropathy": "mitochondrial",
    "MELAS syndrome": "mitochondrial",
    "MERRF syndrome": "mitochondrial",
    "Gilbert syndrome": "autosomal_recessive"
}